### ISSUE TITLE
[Fix] reservation 관련 api 수정

### ISSUE THREAD

**Issue by Young-Yeong** [YU-RentCar/YURentCar-be#107]
## 💡 Issue
reservation 관련 api 수정
## 📝 todo
- [x] 예약 상세 조회 시 photoUrl 추가
- [x] 예약 리스트 조회 시 photoUrl 추가
- [x] 예약 요청 시 reason 추가
- [x] 예약 요청 시 drivers 추가

**Comment by Capoomaru** [comment]
## 💡 어떤 기능을 수정하나요?
특정 예약에서 변경 가능한 차량 리스트를 가져오는 기능에서 오류를 수정합니다.

## 📝 todo
- [x] 특정 예약에서 변경 가능한 차량 리스트를 가져오는 기능 수정
