### ISSUE TITLE
[Feat] Enum 매핑(converter) 구축하기

### ISSUE THREAD

**Issue by Capoomaru** [YU-RentCar/YURentCar-be#24]
## 💡 Issue
자바 상의 enum과 DB내의 데이터를 서로 매핑하기 위한 Converter 클래스를 만들고 아래의 공통 Converter를 구축하여 반복되는 코드를 제거
## 📝 todo
- [x] Enum <-> DBValue
- [x] EnumSet <-> Boolean List
- [x] EnumSet <-> Bitmap(int)
- [x] EnumSet <-> String List

**Comment by Capoomaru** [comment]
#🔥 Issue
* Bitmap type equals 수정
   * EnumSet 자체의 equals로 실행 시 다시 영속성에서 동일 여부 파악 못함
   -> 수정
      1. EnumSet size 동일 여부 체크
      2. EnumSet 끼리 containsAll로 모든 원소 동등성 검사

**Comment by Capoomaru** [comment]
# 🧯 Issue Clear
 - EnumSet 자체의 equals로 실행 시 다시 영속성에서 동일 여부 파악 못함
    - 기존 : enumset.eqauls()
    - 수정 : enumset.size() & enumset.containsall()
```Java
@Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TransmissionBitmap that = (TransmissionBitmap) o;

        //EnumSet 의 equals 을 위해 모두 포함하고 있는지 검사
        if(enumSet.size() != that.enumSet.size())
            return false;
        
        return that.enumSet.containsAll(enumSet);
    }
```
[관련 정리한 노션](https://capoomaru.notion.site/Spring-JPA-dfef1ba39e3b46f3ace763e606ee97be)

**Comment by Capoomaru** [comment]
# 🔥 Issue
* request에서 한글 -> enum 변환 과정에서 desc가 아닌 dbValue를 통해 변환 과정 거침
   -> 수정
      1. EnumValueConvertUtils에 ofDesc 메소드 추가
