### ISSUE TITLE
[Feat] User Entity 관련 API 개발

### ISSUE THREAD

**Issue by Ghanadara** [YU-RentCar/YURentCar-be#27]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 유저 Entity 관련 API를 개발합니다.

## 📝 todo

- [x] 닉네임 중복 체크
- [x] 회원가입 추가 정보
- [x] 소셜로그인
- [x] 닉네임 변경
- [x] 개인정보 수정

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 유저 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 사용자 운전면허증 조회

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 유저 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 예약controller에서 사용자controller로 이동
