### ISSUE TITLE
[Feat] Reservation Entity 관련 API 개발

### ISSUE THREAD

**Issue by Capoomaru** [YU-RentCar/YURentCar-be#61]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 예약 Entity 관련 API를 개발합니다.

## 📝 todo

- [x] 차량 예약 완료

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 예약 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 렌트하기 전인 예약의 자동차 사고내역 조회
- [ ] 렌트하기 전인 예약의 자동차 수리내역 조회
- [ ] 렌트하기 전인 예약의 금액 조회
- [ ] 렌트하기 전인 예약의 자동차 조회
- [ ] 렌트하기 전인 예약의 자동차 제원 조회
- [ ] 렌트하기 전인 예약의 지점 위도 경도 조회
- [ ] 렌트하기 전인 예약 조회

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 예약 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 사용자 과거 예약 조회

**Comment by Capoomaru** [comment]
not done

**Comment by Capoomaru** [comment]
완료

**Comment by Young-Yeong** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 예약 Entity 관련 API를 개발합니다.

## 📝 todo
- [ ] 예약 취소

**Comment by Capoomaru** [comment]
## 💡 어떤 기능을 구현하나요?
지점의 예약 조회와 예약의 시작/끝 시간 조회, 예약 변경을 위한 API를 개발합니다.

## 📝 todo
- [ ] 지점의 예약 조회
  - [ ] 상태별 필터링을 포함
- [ ] 예약의 시작/끝 시간 조회
- [ ] 예약 변경

**Comment by Capoomaru** [comment]
## 💡 어떤 기능을 구현하나요?
지점의 예약 조회와 예약의 시작/끝 시간 조회, 예약 변경을 위한 API를 개발합니다.

## 📝 todo
- [x] 지점의 예약 조회
  - [x] 상태별 필터링을 포함
- [x] 예약의 시작/끝 시간 조회
- [x] 예약 변경
