### ISSUE TITLE
[Feat] Car Entity 관련 API 개발

### ISSUE THREAD

**Issue by Capoomaru** [YU-RentCar/YURentCar-be#62]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 차량 Entity 관련 API를 개발합니다.

## 📝 todo

- [x] 특정 지점에 존재하는 차량 리스트 조회
- [x] 특정 차량에 대한 정보 조회

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 차량 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 차량 크기 리스트 조회
- [ ] 연료 타입 리스트 조회
- [ ] 구동기 리스트 조회

**Comment by Capoomaru** [comment]
개발 완료

**Comment by Capoomaru** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 차량 Entity 관련 API를 개발합니다.

## 📝 todo

- [ ] 차량번호로 렌트 대기 중인 차량 정보 조회
- [ ] 차량번호로 렌트 대기 중인 차량 제원 조회
- [ ] 차량번호로 렌트 대기 중인 차량 수리내역 조회
- [ ] 차량번호로 렌트 대기 중인 차량 사고내역 조회

**Comment by Ghanadara** [comment]
## 💡 어떤 기능을 구현하나요?
API 명세서에 따라 차량 Entity 관련 API를 개발합니다.

## 📝 todo

- [x] 최근 본 차량 리스트 조회

**Comment by Young-Yeong** [comment]
## 💡 어떤 기능을 구현하나요?
차량 사진 등록 개발합니다.

## 📝 todo
- [x] 차량 사진 등록
