### ISSUE TITLE
[Feat] 시도 관련 enum 구현

### ISSUE THREAD

**Issue by Capoomaru** [YU-RentCar/YURentCar-be#66]
## 💡 어떤 기능을 구현하나요?
 지역군(시/도) 분류를 위한 enum 추가 작업

## 📝 todo

- [x] 시도에 대한 enum 생성
- [x] Branch Entity 수정
- [x] 시도를 사용 중인 클래스 수정
